[package]
name = "buffons_needle"
version = "0.1.0"
authors = ["thmeek1 <thmeek1@catamount.wcu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
